language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
install:
  - pip install .
  - pip install -r requirements.txt
script:
  - python setup.py test
notifications:
  email:
	  - ouafi@ouafi.net