language: python
python:
- '3.6'
install:
- python setup.py install
script:
- pip install flask
- pip install Frozen-Flask
- pip install python-frontmatter
- pip install mistune
- bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "426384d6f939"
  - COMMIT_AUTHOR_EMAIL: "you@example.com"
notifications:
  email:
  - ouafi@ouafi.net
before_install:
- openssl aes-256-cbc -K $encrypted_426384d6f939_key -iv $encrypted_426384d6f939_iv
  -in deploy_key.enc -out deploy_key -d
